<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="1332" started-at="2022-02-01T14:21:03 EST" finished-at="2022-02-01T14:21:04 EST">
    <groups>
    </groups>
    <test name="threetierJavaexample" duration-ms="1332" started-at="2022-02-01T14:21:03 EST" finished-at="2022-02-01T14:21:04 EST">
      <class name="dev.revature.tests.playerdaos.PlayerDAOTests">
        <test-method status="PASS" signature="createPlayer()[pri:0, instance:dev.revature.tests.playerdaos.PlayerDAOTests@66a3ffec]" name="createPlayer" duration-ms="927" started-at="2022-02-01T14:21:03 EST" finished-at="2022-02-01T14:21:04 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPlayer -->
        <test-method status="FAIL" signature="deletePlayer()[pri:0, instance:dev.revature.tests.playerdaos.PlayerDAOTests@66a3ffec]" name="deletePlayer" duration-ms="1" started-at="2022-02-01T14:21:04 EST" finished-at="2022-02-01T14:21:04 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at dev.revature.tests.playerdaos.PlayerDAOTests.deletePlayer(PlayerDAOTests.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePlayer -->
        <test-method status="PASS" signature="getAllPlayers()[pri:0, instance:dev.revature.tests.playerdaos.PlayerDAOTests@66a3ffec]" name="getAllPlayers" duration-ms="165" started-at="2022-02-01T14:21:04 EST" finished-at="2022-02-01T14:21:04 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllPlayers -->
        <test-method status="PASS" signature="selectPlayerById()[pri:0, instance:dev.revature.tests.playerdaos.PlayerDAOTests@66a3ffec]" name="selectPlayerById" duration-ms="63" started-at="2022-02-01T14:21:04 EST" finished-at="2022-02-01T14:21:04 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectPlayerById -->
        <test-method status="PASS" signature="selectPlayerByIdFail()[pri:0, instance:dev.revature.tests.playerdaos.PlayerDAOTests@66a3ffec]" name="selectPlayerByIdFail" duration-ms="66" started-at="2022-02-01T14:21:04 EST" finished-at="2022-02-01T14:21:04 EST">
          <exception class="dev.revature.customexceptions.PlayerNotFound">
            <message>
              <![CDATA[Player not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[dev.revature.customexceptions.PlayerNotFound: Player not found
at dev.revature.daos.player.PlayerDAOImp.getPlayerById(PlayerDAOImp.java:42)
at dev.revature.tests.playerdaos.PlayerDAOTests.selectPlayerByIdFail(PlayerDAOTests.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- dev.revature.customexceptions.PlayerNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectPlayerByIdFail -->
        <test-method status="FAIL" signature="updatePlayer()[pri:0, instance:dev.revature.tests.playerdaos.PlayerDAOTests@66a3ffec]" name="updatePlayer" duration-ms="1" started-at="2022-02-01T14:21:04 EST" finished-at="2022-02-01T14:21:04 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at dev.revature.tests.playerdaos.PlayerDAOTests.updatePlayer(PlayerDAOTests.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updatePlayer -->
      </class> <!-- dev.revature.tests.playerdaos.PlayerDAOTests -->
    </test> <!-- threetierJavaexample -->
  </suite> <!-- Default Suite -->
</testng-results>
